version: '3'
services:
  nginx:
    image: nginx
    ports:
     - "9000:80"
    volumes:
     - .:/www
    environment:
     - NGINX_PORT=80
    links:
     - php
    command: [nginx-debug, '-g', 'daemon off;']
  php:
    image: php